/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    VxuButton: typeof import('@vxu-ui/vxu-ui')['Button']
    VxuInput: typeof import('@vxu-ui/vxu-ui')['Input']
  }
}
